### ISSUE TITLE
Empty response from Nuster for content in cache

### ISSUE THREAD

**Issue by dario30186** [jiangwenyuan/nuster#40] opened 2019-03-22 18:16 UTC
Hi,
2 days ago I installed Nuster on my server ubuntu, with image docker nuster/nuster:2.0.8.18.

Here is my configuration:
```
global
        maxconn 4096
        user root
        group root
        daemon
        log 127.0.0.1 local0 debug
        tune.ssl.default-dh-param 2048
        nuster cache on data-size 200m

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option redispatch
        option http-server-close
        option forwardfor
        maxconn 2048
        timeout connect 5s
        timeout client  15min
        timeout server  15min
 
frontend http
       bind *:80
       mode http
       bind *:443 ssl crt /etc/nuster/certs/xxx.com.pem
       reqadd X-Forwarded-Proto:\ https
       http-request redirect prefix http://%[hdr(host),regsub(^www\.,,i)] code 301 if { hdr_beg(host) -i www. }

#ACL letsencrypt
       acl letsencrypt-acl path_beg /.well-known/acme-challenge/
       use_backend letsencrypt-backend if letsencrypt-acl

#ACL API
       acl bm-api_www      hdr_beg(host) -i www.xxx.com
       acl bm-api          hdr_beg(host) -i xxx.com
       use_backend srvs_bm-api if bm-api_www
       use_backend srvs_bm-api if bm-api

backend srvs_bm-api
        nuster cache on
        nuster rule fixtures ttl 10 if { path_beg /xxx/data }
        redirect scheme https if !{ ssl_fc }
        server srvs_bm-api_dev_1 8080

```

This morning nuster started to send empty response for cache content. I was obliged to restart my docker. 
Do you have any idea about this problem?
thank you

**Comment by dario30186** [comment] 2019-03-22 18:41
Should I purge cache manually ? Is it possible that cache was full ?

**Comment by jiangwenyuan** [comment] 2019-03-23 05:50
@dario30186 Hi, could you elaborate more? What exactly does `empty response` mean? TTL is set to 10s, so the cache becomes invalid after 10s.

**Comment by dario30186** [comment] 2019-03-23 10:51
It means that for all the time the content was in the cache(10 seconds), nuster responded with empty body. I think that it knew the content was cached but it didn’t find it. After 10 seconds, the ttl expired and I got the correct response from API. Then the content was cached again and the problem still there. 
I think that the memory was full and nuster tried to cache new requests without success

**Comment by jiangwenyuan** [comment] 2019-03-23 11:06
I see, so you got a response with header and empty body? Does the request go to backend? Could you enable debug and post the debug log here? 
If there's not enough memory, nuster will just forward the request to and the response from origin.

**Comment by dario30186** [comment] 2019-03-23 11:17
The request didn’t go to backend. I didn’t check for headers. 
How can I activate debug mode? Where the log file is? 
Actually I don’t have any errors because I restarted docker. 
If the memory is full, nuster does not free memory from older requests? 
In order to cache new requests I should purge manually?

**Comment by jiangwenyuan** [comment] 2019-03-23 11:35
Could you run 

    docker run -d -p 8080:8080 -v $PWD/nuster.cfg:/nuster.cfg:ro nuster/nuster /usr/local/sbin/nuster -d -f /nuster.cfg

then you can use `docker logs` to see the log

>  If the memory is full, nuster does not free memory from older requests?
> In order to cache new requests I should purge manually?
The expired cache will get deleted no matter the memory is full or not.
But if you set the ttl to 0 which means the cache does not expire, then the cache won't got evicted even if the memory is full. (which is on the todo list)

**Comment by pakit84** [comment] 2019-03-23 19:18
Hello @jiangwenyuan ,
I work with Dario and I am replying on his behalf as he cannot do it right now.
We just had again the same problem, and we had to restart again the nuster compose. It happened after 31 hours he was up.

Before to restart the compose I executed the docker logs command and it gave to me the following : 

[WARNING] 081/191118 (1) : parsing [/etc/nuster/nuster.cfg:35] : a 'http-request' rule placed after a 'reqadd' rule will still be processed before.

**Comment by jiangwenyuan** [comment] 2019-03-24 03:50
Hi @pakit84 
Thanks, that warning happens on startup stage, you can just ignore it.
Could you run following docker command directly instead of compose to get more detailed debug logs?

    docker run -d -p 8080:8080 -v $PWD/nuster.cfg:/nuster.cfg:ro nuster/nuster /usr/local/sbin/nuster -d -f /nuster.cfg

And when it failes again, could you run `curl -vv http://***` to get more detailed response before you restart? (I need to know what exactly `empty response` is, empty header and empty body? )

I presume there's  some kind of test script continuously sending requests to nuster after you started nuster, as the ttl is set to 10s. 
What happens if you run the test script against backend directly? Will the empty response happen?

**Comment by pakit84** [comment] 2019-03-25 08:48
Hello @jiangwenyuan ,

I've run the command you provided. Let's see it it happens again ad I will post the logs.
If I run the script against the backend directly it works, it's a test I did the first time it happens.

**Comment by pakit84** [comment] 2019-03-27 15:02
Hello @jiangwenyuan ,
it happened again.
I've deactivated nuster for now, as it keeps happening more or less after 24 hours.
docker logs gave me more ore less 200mb of logs all of the following type:

00000000:srvs_bm-api.srvrep[0009:000a]: HTTP/1.1 200
00000000:srvs_bm-api.srvhdr[0009:000a]: Access-Control-Allow-Origin: *
00000000:srvs_bm-api.srvhdr[0009:000a]: Content-Encoding: gzip
00000000:srvs_bm-api.srvhdr[0009:000a]: Content-Type: application/json
00000000:srvs_bm-api.srvhdr[0009:000a]: Content-Length: 4029
00000000:srvs_bm-api.srvhdr[0009:000a]: Date: Mon, 25 Mar 2019 08:45:16 GMT
00000000:srvs_bm-api.srvhdr[0009:000a]: Connection: close
00000000:srvs_bm-api.srvcls[0009:adfd]
00000001:http.clireq[0009:ffffffff]: GET /betmines/v1/bets/6411 HTTP/1.1
00000001:http.clihdr[0009:ffffffff]: Content-Type: application/json
00000001:http.clihdr[0009:ffffffff]: Host: api.betmines.com
00000001:http.clihdr[0009:ffffffff]: Connection: Keep-Alive
00000001:http.clihdr[0009:ffffffff]: Accept-Encoding: gzip
00000001:http.clihdr[0009:ffffffff]: User-Agent: okhttp/3.10.0

are they useful for you?
I am getting the header correctly, but not the body. It seems 
![nuster error](https://user-images.githubusercontent.com/17103263/55086697-1d226800-50a9-11e9-8ff9-e534ba29db88.jpeg)

I attached the error we have in our application, hope can help.

Thank you

**Comment by jiangwenyuan** [comment] 2019-03-27 23:55
@pakit84 Thanks, that would be helpful.

Do you still have the container, as I would like to know the cache related logs, something like following:

```
### accept request from client
00000000:web1.accept(0004)=0008 from [127.0.0.1:46424] ALPN=<none>
00000000:web1.clireq[0008:ffffffff]: GET / HTTP/1.1
00000000:web1.clihdr[0008:ffffffff]: Host: 127.0.0.1:9999
00000000:web1.clihdr[0008:ffffffff]: User-Agent: curl/7.61.0
00000000:web1.clihdr[0008:ffffffff]: Accept: */*

### nuster cache related logs
[CACHE] Checking rule: all
[CACHE] Calculate key: method.scheme.host.uri.
[CACHE] Got key: GETHTTP127.0.0.1:9999/
[CACHE] Checking key existence: NOT EXIST
[CACHE] [REQ] Checking if rule pass: PASS
### response:
00000000:app1.srvrep[0008:0009]: HTTP/1.1 200 OK
00000000:app1.srvhdr[0008:0009]: Server: nginx/1.14.0
00000000:app1.srvhdr[0008:0009]: Date: Wed, 27 Mar 2019 23:51:09 GMT
00000000:app1.srvhdr[0008:0009]: Content-Type: text/html
00000000:app1.srvhdr[0008:0009]: Content-Length: 4925
00000000:app1.srvhdr[0008:0009]: Last-Modified: Wed, 07 Nov 2018 12:13:12 GMT
00000000:app1.srvhdr[0008:0009]: Connection: keep-alive
00000000:app1.srvhdr[0008:0009]: ETag: "5be2d6d8-133d"
00000000:app1.srvhdr[0008:0009]: Accept-Ranges: bytes
[CACHE] [RES] Checking status code: PASS
[CACHE] To create
### to create cache
00000001:web1.clicls[adfd:ffffffff]
00000001:web1.closed[adfd:ffffffff]
### another request should use cache
00000002:web1.accept(0004)=0008 from [127.0.0.1:46428] ALPN=<none>
00000002:web1.clireq[0008:ffffffff]: GET / HTTP/1.1
00000002:web1.clihdr[0008:ffffffff]: Host: 127.0.0.1:9999
00000002:web1.clihdr[0008:ffffffff]: User-Agent: curl/7.61.0
00000002:web1.clihdr[0008:ffffffff]: Accept: */*
[CACHE] Checking rule: all
[CACHE] Calculate key: method.scheme.host.uri.
[CACHE] Got key: GETHTTP127.0.0.1:9999/
[CACHE] Checking key existence: EXIST
[CACHE] Hit
### hit, send cached response to client 
00000002:app1.srvrep[0008:ffffffff]: HTTP/1.1 200 OK
00000002:app1.srvhdr[0008:ffffffff]: Server: nginx/1.14.0
00000002:app1.srvhdr[0008:ffffffff]: Date: Wed, 27 Mar 2019 23:51:09 GMT
00000002:app1.srvhdr[0008:ffffffff]: Content-Type: text/html
00000002:app1.srvhdr[0008:ffffffff]: Content-Length: 4925
00000002:app1.srvhdr[0008:ffffffff]: Last-Modified: Wed, 07 Nov 2018 12:13:12 GMT
00000002:app1.srvhdr[0008:ffffffff]: ETag: "5be2d6d8-133d"
00000002:app1.srvhdr[0008:ffffffff]: Accept-Ranges: bytes
00000003:web1.clicls[adfd:ffffffff]
00000003:web1.closed[adfd:ffffffff]
```

**Comment by pakit84** [comment] 2019-03-28 10:41
Hello @jiangwenyuan ,

I have 360mb of logs, which is for you the best way I can give the file to you?

Cheers.

**Comment by jiangwenyuan** [comment] 2019-03-28 12:55
Hi @pakit84 

Could you grep the log of the failed request?

**Comment by jiangwenyuan** [comment] 2019-03-28 13:14
Hi @pakit84 

Could you grep the log of the failed request? 

What is the http server?

I just find out that the status line in your log does not have a reason phrase, which is normally `OK` for 200 status code.

```
00000000:srvs_bm-api.srvrep[0009:000a]: HTTP/1.1 200
00000000:srvs_bm-api.srvhdr[0009:000a]: Access-Control-Allow-Origin: *
```

Could this be the reason why your okhttp client complains about `Unexpected status line` ?

**Comment by dario30186** [comment] 2019-03-30 12:34
Hi @jiangwenyuan ,
here is the complete log:
https://drive.google.com/file/d/1_DGY3Gng9F41HQD751DlBkVleV6ETrck/view?usp=sharing

our http server is a Jersey API. It would be great if we find a solution, Nuster is great and I hope the log is useful for you to find the problem

**Comment by dario30186** [comment] 2019-03-30 12:36
I don't know why the API response is just HTTP/1.1 200 but Nuster works fine for about 24 hours and then we start getting errors

**Comment by dario30186** [comment] 2019-03-30 12:43
Our server is Tomcat 8.5.x
As for the current HTTP/1.1 specification, the reason phrase is optional and Tomcat does not provide it by default in version 8.5.x and it is gone in version 9.x

**Comment by jiangwenyuan** [comment] 2019-03-30 13:26
@dario30186 Thanks, do you know the request path of the failed response?

**Comment by dario30186** [comment] 2019-03-30 13:52
You can check /fixtures with query param ‘from’ and ‘to’ and fixtures/live

**Comment by jiangwenyuan** [comment] 2019-03-30 16:03
@dario30186 thanks, the log seems fine.

According to the source code of okhttp:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/StatusLine.java#L53

and the image you posted, seems that either the prior response was not properly handled or the response was malformed, as there is extra data `4***` before the next response. 
For example, the content-length is 100 while the real body size is 104. It's hard to tell who's the culprit based on existing information.
Does this error ever happen again after you removed nuster?
Is it possible to provide a reproducible environment(dockerfile, etc)?

**Comment by dario30186** [comment] 2019-03-30 22:27
@jiangwenyuan if we remove nuster and use standard haproxy the problem never occurs. 
It’s very strange that the problem is only present after ~24 hours. The cache is like full and nuster does not reply as expected. 
Our response in zipped for some endpoints, that could be a problem for nuster?

**Comment by jiangwenyuan** [comment] 2019-03-31 02:44
@dario30186  
> if we remove nuster and use standard haproxy the problem never occurs. 

I see...

> It’s very strange that the problem is only present after ~24 hours. The cache is like full and nuster does not reply as expected. 

What happens if you change data-size to 20m or 400m? Will this change the time when the error occurs?

> Are old responses with an expired TTL purged automatically from cache? How the cache can be full if only responses with a valid TTL shoud still stay in the cache? 

Yes, old responses with an expired TTL are purged automatically. If the cache is full, nuster serves cached response if there's a HIT but stops caching anything and just acts as http load balancer for new requests, and will continue to cache when expired cache gets deleted.

> Our response is zipped for some endpoints, that could be a problem for nuster?

No, nuster works fine with zipped contents.

> We can’t provide a dockerfile because it’s a private image and we can’t share it. 

Is there any way you could help me reproduce this issue? Is it possible to sanitize the image and send it to me by email(you can find in git log or README.me)?

Thanks

**Comment by dario30186** [comment] 2019-04-02 08:39
@jiangwenyuan sorry for the late response. We can only test next weekend. We will let you know

**Comment by dario30186** [comment] 2019-04-05 15:21
Hi @jiangwenyuan,
we check the tomcat log and we noticed that sometimes there is a "broken pipe" error because the API cannot write json correctly. Maybe this could be cause the problem because nuster cache the bad response and response to client with the bad content.

But by default, nuster should only cache 200 OK response, isn't it? 
So maybe, the jersey API set http status to 200 OK but then the body is not correctly written for some reasons.

**Comment by jiangwenyuan** [comment] 2019-04-06 03:30
@dario30186 
Yes, only 200 OK response is cached by default.

It might be possible, I'm not sure... I'm still concerned about the `unexpected status line` error, trying to look into the source code.
Please inform me if you have new updates, thanks

**Comment by dario30186** [comment] 2019-04-06 09:42
@jiangwenyuan we have this nuster configuration for server:
`backend srvs_bm-api
        nuster cache on
        nuster rule fixtures ttl 10 if { path_beg /application/v1/fixtures }
        redirect scheme https if !{ ssl_fc }
        server srvs_bm-api_dev_1 172.17.0.1:8080`

but requests of type https://api.domain.com/application/v1/fixtures/?from=2019-03-30&to=2019-04-04

are not cached. If we make 2 requests in 2 seconds, nuster redirect both requests to api.
any idea?

the current configuration is that in my first post. We make some tests to try to reproduce the bug

**Comment by dario30186** [comment] 2019-04-08 06:14
@jiangwenyuan  UPDATE: the cache works fine. The 2 requests I made had different query parameters, that's why nuster redirected them to API.

We continue investigation about the problem and will let you know ;)

**Comment by jiangwenyuan** [comment] 2019-04-08 14:53
Hi, thank you so much for your time:)

**Comment by dario30186** [comment] 2019-04-11 06:44
Hi @jiangwenyuan,
yesterday night a problem occurred with Nuster. Suddenly I didn't cache requests anymore. We didn't get any errors , but simply it redirected all requests to API.
This caused high CPU usage like in attached file.
![cpu](https://user-images.githubusercontent.com/29282727/55935951-2ed14700-5c35-11e9-9936-fb0a9c7c4875.png)

After restarting nuster everything was fine again.
I guess the cache was full and nuster didn't purge it. But we only have 4 cached requests and it's impossible that they take all 200m of memory allocated for nuster. 
Maybe there is a problem with cache purging when we are in a docker container ?

**Comment by dario30186** [comment] 2019-04-11 21:58
I tried with data-size 200M but after a few hours the problem occurred again.
Nuster does not cache requests. 
I run the command :
docker stats

before restarting nuster in order to see how much memory nuster was cosuming and the memory usage was 11.98MiB. 
We have 350 requests per minute, maybe is too much for nuster?

**Comment by dario30186** [comment] 2019-04-13 09:14
Hi again @jiangwenyuan , 
maybe the problem is caused by an incorrect length size that occurs randomly.
We don't know yet is it's caused by nuster or our API. 
Anyway, nuster does not cache requests anymore after 1 or 2 hours of running. 
When I restart nuster docker then we have 200M of memory freed, so I guess that nuster does not purge cache and that's why he does not cache requests after some time.
We have ~600 req/s

**Comment by jiangwenyuan** [comment] 2019-04-13 23:46
Hi @dario30186 

Thanks. 

> I guess the cache was full and nuster didn't purge it. But we only have 4 cached requests and it's impossible that they take all 200m of memory allocated for nuster.

If you set ttl to 10, nuster will purge it.

> Maybe there is a problem with cache purging when we are in a docker container ?

It does not matter.

> Does 200m means 200 megabit ?

Yes

> We have 350 requests per minute, maybe is too much for nuster?

No, it can handle much more

>  maybe the problem is caused by an incorrect length size that occurs randomly.
We don't know yet is it's caused by nuster or our API.

I also want to find out, only if I can reproduce it

> When I restart nuster docker then we have 200M of memory freed, so I guess that nuster does not purge cache and that's why he does not cache requests after some time.

nuster does not support automatical cache replacement like LRU. But if you set the ttl to 10, there's the possibility that the memory is full before the expired cache gets evicted.

You can check the cache usage according to https://github.com/jiangwenyuan/nuster#cache-stats
You can also change the data_size.

**Comment by dario30186** [comment] 2019-04-16 17:07
Hi @jiangwenyuan,
some important news about investigation.

We can reproduce the bug, it comes from nuster. 
Here is our nuster configuration in global section:
nuster cache on data-size 2m uri /nuster

so just 2 megabyte of cache. 
We run nuster and begun making requests to our API.
After some requests and 2 minutes the cache is full. If I run command curl http://127.0.0.1/nuster I have this response:

**GLOBAL**
global.nuster.cache.data.size: 2097152
global.nuster.cache.dict.size: 1048576
global.nuster.cache.uri: /nuster
global.nuster.cache.purge_method: PURGE
global.nuster.cache.stats.used_mem: 1986260
global.nuster.cache.stats.req_total: 33
global.nuster.cache.stats.req_hit: 0
global.nuster.cache.stats.req_fetch: 4
global.nuster.cache.stats.req_abort: 0

**PROXY srvs_bm-api_dev 2**
srvs_bm-api_dev.rule.fixtures: state=on ttl=1000
srvs_bm-api_dev.rule.bets: state=on ttl=10
srvs_bm-api_dev.rule.countries: state=on ttl=10

as you can see we set ttl=1000 (~16 minutes) for our API so after 2 minutes the cache is still valid. 

From the time the memory is full on, if we execute some requests then nuster always redirect them to API but we get a valid response ONLY IF the api response contains Header Content-Length. 
Instead, if API response contains Header "Transfer-Encoding →chunked" (because the body is large) then maybe nuster does not wait for all chunks and tries to respond with the first received chunk from API. 
NB Transfer-Encoding →chunked is a standard for HTTP 1.1.
NB if cache is not full, nuster correctly handles chunked responses, the problem only starts when chache is full.
Can you check in your code please?


In addition, if we wait 20 minutes in order to invalidate cache content and then I run command curl http://127.0.0.1/nuster , the memory is always full. 
global.nuster.cache.stats.used_mem: 1986260

even if TTL is expired. Do you have any idea why the memory is not automatically purged as soon as TTL expires?

**Comment by jiangwenyuan** [comment] 2019-04-16 22:01
Hi @dario30186, thanks so much,this is very helpful for me to reproduce the issue.
I'll look into it

**Comment by dario30186** [comment] 2019-04-19 22:31
hi @jiangwenyuan , did you reproduce this issue? do you already know how to fix it ?
if you need any help for testing, do not hesitate to ask ;)

**Comment by jiangwenyuan** [comment] 2019-04-20 11:21
Hi @dario30186 , Not yet, are you able to 100% produce the bug ?

**Comment by dario30186** [comment] 2019-04-20 11:25
Yes, I can reproduce it ;)

**Comment by jiangwenyuan** [comment] 2019-04-20 15:02
@dario30186 Does the backend have to be your API server? Any chance to reproduce the bug with some sample code or apache/nginx backend? I've tried many ways but failed to reproduce. 

Thanks

**Comment by dario30186** [comment] 2019-04-20 17:57
I think that you just need a backend that returns a large gzip body and header Transfer-Encoding →chunked

**Comment by jiangwenyuan** [comment] 2019-04-22 01:12
HI @dario30186 

I still couldn't reproduce the issue using your method, but I found an unrelated but potential flaw that might lead to the issue.

Will try to look more into this

**Comment by maeteem** [comment] 2019-04-22 09:27
Hi @jiangwenyuan 
I use nuster for cache HTTP Live Streaming and got cache full problem too.
global.nuster.cache.stats.used_mem not return to 0 after PURGE all cache.
I think I can reproduce cache does expire issue using Apache HTTP server benchmarking tool.
1. fill cache using: 
`curl http://192.168.1.1:8080/258.1245209447.mp4 > /dev/null`
2. run Apache HTTP server benchmarking tool with 2 concurrent connection:
`ab -n 2 -c 2 http://192.168.1.1:8080/258.1245209447.mp4`
3. PURGE all cache:
`curl -X PURGE -H "name: all" http://192.168.1.1:8080/nuster`
4. display cache stats, used_mem dose not return back to 0:
`http://192.168.1.1:8080/nuster`
```
**GLOBAL**
global.nuster.cache.data.size: 104857600
global.nuster.cache.dict.size: 1048576
global.nuster.cache.uri: /nuster
global.nuster.cache.purge_method: PURGE
global.nuster.cache.stats.used_mem: 165326
global.nuster.cache.stats.req_total: 3
global.nuster.cache.stats.req_hit: 2
global.nuster.cache.stats.req_fetch: 1
global.nuster.cache.stats.req_abort: 0

**PROXY nginx 3**
nginx.rule.all: state=on ttl=180
```
Here is my configuration:
```
global
        stats timeout 2m
        log /dev/log local0  info
        nuster cache on data-size 100m uri /nuster

defaults
        timeout connect 10s
        timeout client 30s
        timeout server 30s
        option httplog
        log global
        mode http

frontend http-in
        bind 192.168.1.1:8080
        acl valid_http_method method GET
        default_backend nginx

backend nginx
        nuster cache on
        nuster rule all ttl 180 code 200
        server nginx1 192.168.1.2:81
```
hope this is useful for you to find the problem

**Comment by jiangwenyuan** [comment] 2019-04-22 11:13
Hi @dario30186 @maeteem 

Could you please test using https://github.com/jiangwenyuan/nuster/tree/issue40 branch?

BTW, when you purge cache, the cache will be marked as invalid only. The memory will be released in further circles. So the `used_mem` might not change after the purge, as the memory does not get free-ed immediately.

**Comment by dario30186** [comment] 2019-04-22 18:22
Hi @jiangwenyuan, I will test the branch tomorrow morning.
I will let you know ;)

**Comment by dario30186** [comment] 2019-04-23 16:31
Hi @jiangwenyuan,
I built the nex branch and it I am not able to reproduce the bug anymore, so I think that you fixed the issue :) 
What was the problem ? Just to understand 

Let me know if you build a docker release with this new version.
Thank you very much

**Comment by jiangwenyuan** [comment] 2019-04-24 00:07
@dario30186 Cool! thanks so much.

The problem was caused by a corrupted buffer pointer. When forwarding the first chunk of response, if there are header and part of the body and if the allocation of memory for the body fails due to insufficient memory, the buffer pointer does not get rewound, so irrelevant  data is sent to the client instead which cause an unmatched length and size of the content.

Thank you so much for your time and help, I'll release a new version very soon

**Comment by jiangwenyuan** [comment] 2019-04-24 14:33
@dario30186 Released docker image, could you please test?
Thanks

**Comment by dario30186** [comment] 2019-04-24 15:46
@jiangwenyuan when I try to pull new nuster image nuster/nuster:2.1.1.19  from docker-compose I get en error:
Pulling nuster ... error
ERROR: for nuster  b'manifest for nuster/nuster:2.1.1.19 not found'
ERROR: manifest for nuster/nuster:2.1.1.19 not found

the same occurs if I put nuster/nuster:2.1.1.19-alpine

**Comment by dario30186** [comment] 2019-04-24 16:03
UPDATE 
I used tag "latest" because I saw that you pushed it an hour ago and nuster works well ;)
Can you push docker images with the version tag in hub.docker.com pls ?

**Comment by jiangwenyuan** [comment] 2019-04-25 00:34
@dario30186 Of course, will do. Please let me know if anything goes wrong:)

**Comment by maeteem** [comment] 2019-04-25 10:05
Hi @jiangwenyuan 
I try to solve cache does expire issue and found that HTTP/1.0 client make cache data->clients not decrement after connection close. this make cache data still valid and not free.
I not sure that if we add `appctx->ctx.nuster.cache_engine.data->clients--;` in nst_cache_engine_handler() engine.c line 45 before then return shuoud fix.
Could you please have a look into this.
Thanks,
```
static void nst_cache_engine_handler(struct appctx *appctx) {
    struct nst_cache_element *element = NULL;
    struct stream_interface *si       = appctx->owner;
    struct channel *res               = si_ic(si);
    /* struct stream *s                  = si_strm(si); */
    int ret;

    if(unlikely(si->state == SI_ST_DIS || si->state == SI_ST_CLO)) {
+++     appctx->ctx.nuster.cache_engine.data->clients--;
        return;
    }

```

**Comment by jiangwenyuan** [comment] 2019-04-26 01:54
Hi @maeteem 

It happens when HTTP/1.0 or HTTP/1.1 with `connection: close` header, fixed.
Could you please test with the new version?

Thank you so much

**Comment by maeteem** [comment] 2019-04-26 14:04
I will test and let you known on Monday.
Thanks

**Comment by maeteem** [comment] 2019-04-29 02:46
Update: I run v2.0.10.18 and it works well ;)
Thanks

**Comment by dario30186** [comment] 2019-04-29 16:04
Hi @jiangwenyuan ,
you pushed docker image 2.1.2.19. 
Does this image contains your fix ?

**Comment by jiangwenyuan** [comment] 2019-04-29 21:46
Hi @dario30186 yes, thank you so much

**Closed by jiangwenyuan** 2019-04-29 21:46 UTC
Labels: bug, investigation
