### ISSUE TITLE
When a client aborts the connection, is the full result correctly cached?

### ISSUE THREAD

**Issue by skinkie** [jiangwenyuan/nuster#69] opened 2020-04-21 22:32 UTC
I am currently running a nuster service at tile.openstreetmap.nl and something interesting happens. It seems that several upstream files get only _partially_ stored. I wonder if a file gets cached correctly if the fetching client aborts the connection.

![image](https://user-images.githubusercontent.com/502394/79920545-a46b1800-8430-11ea-9aa1-8bcb51cb0a46.png)

**Comment by packeteer** [comment] 2020-04-21 23:47
hmm, we see similar behaviour with some values not being cached

**Comment by jiangwenyuan** [comment] 2020-04-22 00:01
@skinkie If the client aborts the connection, the response is  cached partially but set to invalid, and will be deleted later. It will never be served to clients.

If you enable debug:

```
00000000:app1.nuster[0016:0017]: [cache] To create
00000000:app1.nuster[0016:0017]: [cache] Created
```
The cache is stored completely and set valid and can be served after `Created`

**Comment by skinkie** [comment] 2020-04-22 09:40
@jiangwenyuan how can we best debug this issue? I don't know how I can **programmatically** trigger this issue, which makes consistent reproducing difficult other than zooming into and out from a map.

**Comment by jiangwenyuan** [comment] 2020-04-22 09:59
@skinkie can you share a reproducible config file?

**Comment by skinkie** [comment] 2020-04-22 10:13
https://github.com/jiangwenyuan/nuster/issues/68#issuecomment-617228085

**Comment by jiangwenyuan** [comment] 2020-04-22 10:23
@skinkie which url should I get? http://127.0.0.1/osm ?

**Comment by jiangwenyuan** [comment] 2020-04-22 10:28
@skinkie Can you tried the latest version and enable debug? And when the error occurs, can you check chrome devtools to find out which url is broken, and check the log to see if the url is cached or not?

**Comment by skinkie** [comment] 2020-04-22 10:29
@jiangwenyuan I'll do so shortly.

**Comment by skinkie** [comment] 2020-04-22 11:29
I can reproduce this with the latest version. Debug is enabled.
```
rm -r /var/tiles/nuster/*
./haproxy -W -d -f /etc/haproxy/haproxy.cfg 1>/tmp/nuster.log 2>&1
```

Half of the tile:
![image](https://user-images.githubusercontent.com/502394/79976580-26912600-849d-11ea-8112-ad0d235fed5c.png)

```
[nuster.log](https://github.com/jiangwenyuan/nuster/files/4515782/nuster.log)

```

**Comment by jiangwenyuan** [comment] 2020-04-22 11:39
@skinkie what is the url of the broken image?

**Comment by skinkie** [comment] 2020-04-22 11:42
https://tile.openstreetmap.nl/osm/12/2114/1351.png

**Comment by jiangwenyuan** [comment] 2020-04-22 12:02
1. Are you using master or v2.0.4.21?

2. What if you stop all other traffics and access https://tile.openstreetmap.nl/osm/12/2114/1351.png, and what's the output?

3. can you gdb -p haproxy-pid and  try `p *nuster.cache.dict.entry[8041175051104540622%nuster.cache.dict.size]`

4. http is fine but https is broken?

5. How can I reproduce it on my side? I can access http://127.0.0.1/osm/5/20/24.png, how can I visit the above map page?

**Comment by skinkie** [comment] 2020-04-22 12:29
1. only running master

2. please clarify; I can try to run this thing locally on my laptop and see if I can reproduce it. But it will still imply I need to do multiple request in order to get Chrome to abort a request. This also suggest this start with HTTP/2

3. (gdb) p *nuster.cache.dict.entry[8041175051104540622%nuster.cache.dict.size]
$1 = {next = 0x0, state = 2, key = {flags = 0 '\000', size = 50, 
    data = 0x7fa68b706100 "GET", hash = 8041175051104540622, 
    uuid = "\277\242\352>\205\347\256\002\026ғY<hE\372S\363\261", <incomplete sequence \316>}, rule = 0x0, buf = {size = 38, 
    area = 0x7fa68b706140 "/12/2114/1351.pngp.nl", data = 0, head = 0}, 
  host = {ptr = 0x7fa68b706140 "/12/2114/1351.pngp.nl", len = 21}, path = {
    ptr = 0x7fa68b706140 "/12/2114/1351.pngp.nl", len = 17}, etag = {
    ptr = 0x0, len = 0}, last_modified = {ptr = 0x0, len = 0}, pid = 0, 
  header_len = 716, payload_len = 34542, expire = 1587576345, ctime = 0, 
  atime = 1587557022251, ttl = 21600, extend = "\000\000\000", access = {0, 0, 
    0, 5}, extended = 0, store = {ring = {data = 0x0, item = 0x0}, disk = {
      file = 0x7fa68b706180 "/var/tiles/nuster/b/bf/bfa2ea3e85e7ae0216d293593c6845fa53f3b1ce"}}}

4. Downloading it via wget with http, still gives half a tile.

5. http://tile.openstreetmap.nl/index2.html now points to //127.0.0.1/osm/ meaning you could run the proxy locally.

**Comment by skinkie** [comment] 2020-04-22 12:36
I have just checked v5.0.4.21 on the server. Sadly: same issue.

**Comment by skinkie** [comment] 2020-04-22 12:40
Preliminary result: when http/2 is disabled, I am unable to reproduce the issue with a clear cache.

**Comment by jiangwenyuan** [comment] 2020-04-22 15:00
@skinkie I successfully created a local system, but could not reproduce it.

So I downloaded needed static files:

```
jwy@localhost issue69 $ ll -R
.:
total 4
drwxrwxr-x 2 jwy jwy   46 Apr 22 23:41 img
-rw-rw-r-- 1 jwy jwy 1731 Apr 22 23:39 index2.html
drwxrwxr-x 4 jwy jwy  183 Apr 22 23:49 local

./img:
total 8
-rw-rw-r-- 1 jwy jwy 1150 Nov 24  2014 nl.ico
-rw-rw-r-- 1 jwy jwy 1211 Nov 24  2014 osm-logo-30x30.jpg

./local:
total 1112
-rw-rw-r-- 1 jwy jwy    833 Jan 12  2010 functions.js
drwxrwxr-x 2 jwy jwy    252 Apr 22 23:51 img
-rw-rw-r-- 1 jwy jwy  57254 Dec 21  2009 jquery-1.3.2.min.js
-rw-rw-r-- 1 jwy jwy   4246 Dec 21  2009 jquery.cookie.js
-rw-rw-r-- 1 jwy jwy   3597 Apr 22 23:21 map2.js
-rw-rw-r-- 1 jwy jwy 982805 Apr 22 23:48 OpenLayers.js
-rw-rw-r-- 1 jwy jwy  74405 Sep 23  2010 proj4js-compressed.js
-rw-rw-r-- 1 jwy jwy   1846 Nov 24  2014 style.css
drwxrwxr-x 3 jwy jwy     21 Apr 22 23:49 theme

./local/img:
total 40
-rw-rw-r-- 1 jwy jwy 342 Jul  4  2011 east-mini.png
-rw-rw-r-- 1 jwy jwy 405 Jul  4  2011 layer-switcher-maximize.png
-rw-rw-r-- 1 jwy jwy 220 Jul  4  2011 layer-switcher-minimize.png
-rw-rw-r-- 1 jwy jwy 378 Jul  4  2011 north-mini.png
-rw-rw-r-- 1 jwy jwy 247 Jul  4  2011 slider.png
-rw-rw-r-- 1 jwy jwy 373 Jul  4  2011 south-mini.png
-rw-rw-r-- 1 jwy jwy 360 Jul  4  2011 west-mini.png
-rw-rw-r-- 1 jwy jwy 350 Jul  4  2011 zoombar.png
-rw-rw-r-- 1 jwy jwy 291 Jul  4  2011 zoom-minus-mini.png
-rw-rw-r-- 1 jwy jwy 386 Jul  4  2011 zoom-plus-mini.png

./local/theme:
total 0
drwxrwxr-x 2 jwy jwy 23 Apr 22 23:49 default

./local/theme/default:
total 12
-rw-rw-r-- 1 jwy jwy 8754 Jul  4  2011 style.css
```

Update the index2.html

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>NL tile-server - OpenStreetMap</title>
  <link rel="shortcut icon" href="img/nl.ico" />
  <meta name="Description" content="Nederlandse OpenStreetMap tile-server" />
  <meta name="Keywords" content="osm,gratis,kaart,map,openstreetmap" />
  <meta name="robots" content="index, follow" />
  <meta http-equiv="Content-Language" content="nl" />
  <script src="/local/OpenLayers.js" type="text/javascript"></script>
  <script src="/local/proj4js-compressed.js" type="text/javascript"></script>
  <script src="/local/map2.js" type="text/javascript"></script>
  <script src="/local/jquery-1.3.2.min.js" type="text/javascript"></script>
  <script src="/local/jquery.cookie.js" type="text/javascript"></script>
  <script src="/local/functions.js" type="text/javascript"></script>
 <link rel="stylesheet" href="/local/style.css" type="text/css" />
</head>
<body onload="init()">
  <div id="map"></div>
  <div id="attribution">
    <a href="//www.openstreetmap.nl"><img src="img/osm-logo-30x30.jpg" alt="OpenStreetMap" /></a>
    <p>Hosting provided by <a href="http://www.oxilion.nl/">Oxilion</a>.</p>
    <p>Map data &copy; 2012 
      <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a> 
      <a href="http://openstreetmap.org">OpenStreetMap.org</a> contributors.</p>
  </div>
  <div id="geoinfo">
    <span id="posLatLon"></span>
    <span id="posRD"></span>
    <span id="permalink"></span> (<span id="editlink"></span>)
    <span id="schaal"></span>
  </div>
</body>
</html>
```

create a local http server:

```
python -m SimpleHTTPServer 8000
```

nuster.cfg:

```
global
        ssl-default-bind-options no-sslv3 no-tls-tickets
        tune.ssl.default-dh-param 2048
        ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
        nuster cache on data-size 1g dir /tmp/nuster
        nuster manager on
        maxconn 10000
        master-worker
        debug
        nbproc 3
        tune.maxaccept -1
defaults
        retries 3
        maxconn 10000
        option redispatch
        option dontlognull
        timeout client  15s
        timeout connect 15s
        timeout server  10s
        http-reuse always
frontend http
        bind *:80
        bind *:443 ssl crt ./certs/nuster.dev.pem alpn h2,http/1.1
        mode http
        acl PATH_osm path_beg -i /osm
        use_backend openstreetmap_org if PATH_osm
        default_backend local
backend openstreetmap_org
        mode http
        http-request set-path %[path,regsub(^/osm/,/)]
        http-request del-header Origin
        http-request del-header Referer
        http-request del-header Cookie
        http-request del-header Via
        http-request del-header Dnt
        http-request del-header upgrade-insecure-requests
        nuster cache on
        nuster rule sync memory on disk on etag on last-modified on ttl 10m
        # server s1 tile.openstreetmap.org:443 weight 1 maxconn 100 check ssl verify none
        server s1 tile.openstreetmap.org:80 weight 1
backend local
        mode http
	nuster cache on
	nuster rule all
        server s3 127.0.0.1:8000
```

everything works fine. But I do observed some requests are cancelled
<img width="1434" alt="Screen Shot 2020-04-23 at 0 00 02" src="https://user-images.githubusercontent.com/19603306/79998286-7996c780-84f5-11ea-9715-db33e43429fc.png">

**Comment by skinkie** [comment] 2020-04-22 15:10
I am trying to reproduce it on my local system as well (including cancelled requests), which does not yet result into an issue either. This may suggest a threading issue...

**Comment by skinkie** [comment] 2020-04-22 15:19
I am consistently able to reproduce this issue on the server with http/2, also with one single worker. Will continue to see if I can reproduce this locally.

**Comment by skinkie** [comment] 2020-04-22 16:55
Why I notice on the server; below is the first time that the tile is requested with an empty client cache and empty proxy cache. As you notice it is requested by "my client". So I was generally the first one. You can see that this tile is served with the size of 43420. This is the **actual size** of the tile. This is also the size of the file that comes from nuster.

...but the cached item (if binary compared lacks about 14k).

[compared.zip](https://github.com/jiangwenyuan/nuster/files/4517720/compared.zip)

So I am quite puzzled how it is possible that the middle of a file is gone.

```
00008e5:http.clireq[001f:ffffffff]: GET https://tile.openstreetmap.nl/osm/8/131/87.png HTTP/2.0
000008e5:http.clihdr[001f:ffffffff]: user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
000008e5:http.clihdr[001f:ffffffff]: accept: image/webp,image/apng,image/*,*/*;q=0.8
000008e5:http.clihdr[001f:ffffffff]: sec-fetch-site: same-origin
000008e5:http.clihdr[001f:ffffffff]: sec-fetch-mode: no-cors
000008e5:http.clihdr[001f:ffffffff]: sec-fetch-dest: image
000008e5:http.clihdr[001f:ffffffff]: referer: https://tile.openstreetmap.nl/
000008e5:http.clihdr[001f:ffffffff]: accept-encoding: gzip, deflate, br
000008e5:http.clihdr[001f:ffffffff]: accept-language: en-US,en;q=0.9,nl;q=0.8
000008e5:http.clihdr[001f:ffffffff]: host: tile.openstreetmap.nl
000008e5:http.clihdr[001f:ffffffff]: cookie: osmnl_lat=51.67661389952163; osmnl_lon=8.169069961501824; osmnl_zoom=8
000008e5:http.nuster[001f:ffffffff]: [cache] ===== attach =====
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [rule ] ----- sync
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [rule ] key:  method.scheme.host.uri.
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [key  ] raw:  |46| GETHTTPStile.openstreetmap.nl/8/131/87.png
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [key  ] hash: 13974269588959873389
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [key  ] uuid: a91d8651f0925505c80aee36606ca33362596766
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [cache] Check key existence: HIT memory
000008e5:openstreetmap_org.srvrep[001f:ffffffff]: HTTP/1.1 200 OK
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: server: nginx
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: date: Wed, 22 Apr 2020 16:26:12 GMT
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: content-type: image/png
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: content-length: 43420
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: expect-ct: max-age=0
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: etag: "e928fb2289f6da7dd9adc655bb9256f5"
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: cache-control: max-age=61465, stale-while-revalidate=604800, stale-if-error=604800
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: expires: Tue, 14 Apr 2020 14:58:49 GMT
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: access-control-allow-origin: *
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: x-tilerender: ysera.openstreetmap.org
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: x-cache: MISS from saphira.openstreetmap.org
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: x-cache-lookup: MISS from saphira.openstreetmap.org:3128
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: via: 1.1 saphira.openstreetmap.org (squid/4.10)
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: x-cache-status: HIT - saphira
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: strict-transport-security: max-age=31536000; includeSubDomains; preload
000008e5:openstreetmap_org.srvhdr[001f:ffffffff]: last-modified: Wed, 22 Apr 2020 16:26:12 GMT
000008e5:openstreetmap_org.nuster[001f:ffffffff]: [cache] ===== detach =====
000008e5:openstreetmap_org.srvcls[001f:ffffffff]
000008e5:openstreetmap_org.clicls[001f:ffffffff]
000008e5:openstreetmap_org.closed[001f:ffffffff]
```

**Comment by skinkie** [comment] 2020-04-22 17:32
I have yet tested disabling multiple parameters. The only consisted fix is to disable HTTP/2.

**Comment by jiangwenyuan** [comment] 2020-04-23 00:08
At least the disk file is corrupted

**Comment by jiangwenyuan** [comment] 2020-04-23 10:25
@skinkie  Should be fixed in https://github.com/jiangwenyuan/nuster/tree/issue69 , can you try?
Thanks

**Comment by skinkie** [comment] 2020-04-23 11:28
There are no "half" tiles anymore. But I do not get any 304 responses anymore.

**Comment by jiangwenyuan** [comment] 2020-04-23 12:10
```
$ curl https://nuster.dev/osm/16/32754/21789.png -v >/dev/null

* TCP_NODELAY set
* Connected to nuster.dev (***) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
....
> GET /osm/16/32754/21789.png HTTP/2
> Host: nuster.dev
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: nginx
< date: Thu, 23 Apr 2020 12:05:04 GMT
< content-type: image/png
< content-length: 28018
< expect-ct: max-age=0
< etag: "09feb7032343edcac6fd8bb3560efb6e"
< cache-control: max-age=13368, stale-while-revalidate=604800, stale-if-error=604800
< expires: Thu, 23 Apr 2020 13:19:47 GMT
< access-control-allow-origin: *
< x-tilerender: bowser.openstreetmap.org
< age: 8885
< x-cache: HIT from longma.openstreetmap.org
< x-cache-lookup: HIT from longma.openstreetmap.org:3128
< via: 1.1 longma.openstreetmap.org (squid/4.10)
< x-cache-status: MISS - longma
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< last-modified: Thu, 23 Apr 2020 12:05:04 GMT
< nuster-cache: hit
< 
{ [14321 bytes data]
100 28018  100 28018    0     0  66709      0 --:--:-- --:--:-- --:--:-- 66551
* Connection #0 to host nuster.dev left intact
* Closing connection 0
$ curl https://nuster.dev/osm/16/32754/21789.png -v >/dev/null -H "if-modified-since: Thu, 23 Apr 2020 12:05:04 GMT"

* TCP_NODELAY set
* Connected to nuster.dev (*****) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1

> GET /osm/16/32754/21789.png HTTP/2
> Host: nuster.dev
> User-Agent: curl/7.64.1
> Accept: */*
> if-modified-since: Thu, 23 Apr 2020 12:05:04 GMT
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 304 
< last-modified: Thu, 23 Apr 2020 12:05:04 GMT
< etag: "09feb7032343edcac6fd8bb3560efb6e"
< nuster-cache: hit

$ curl https://nuster.dev/osm/16/32754/21789.png -v >/dev/null -H 'if-none-match: "09feb7032343edcac6fd8bb3560efb6e"'
  
> GET /osm/16/32754/21789.png HTTP/2
> Host: nuster.dev
> User-Agent: curl/7.64.1
> Accept: */*
> if-none-match: "09feb7032343edcac6fd8bb3560efb6e"
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 304 
< last-modified: Thu, 23 Apr 2020 12:05:04 GMT
< etag: "09feb7032343edcac6fd8bb3560efb6e"
< nuster-cache: hit
< 
{ [0 bytes data]

```

**Comment by skinkie** [comment] 2020-04-23 12:30
Back to the drawing board...

![image](https://user-images.githubusercontent.com/502394/80099268-7986de00-856e-11ea-9dfa-7c22ad0806a3.png)

It seems that now the second time the file is loaded the file is complete transfered from the server.

With respect to 304 messages: I saw in Chrome "200" responses, but they did come from disk cache.

**Comment by skinkie** [comment] 2020-04-23 12:41
![image](https://user-images.githubusercontent.com/502394/80100550-637a1d00-8570-11ea-8931-515d3b793a28.png)
The 404 tiles seem to be "Failed" requests, showing a HTTP2 protocol error.

**Comment by skinkie** [comment] 2020-04-23 13:12
![image](https://user-images.githubusercontent.com/502394/80103677-e00efa80-8574-11ea-8b3b-eeda5b79d98d.png)

**Comment by skinkie** [comment] 2020-04-23 13:53
> Any error on server side in regard to this http2 error?

Not that I am able to see. I do have the debug logs running. One of the suggestions I found on stackoverflow was an invalid content-length not matching bytes transferred.

**Comment by jiangwenyuan** [comment] 2020-04-24 00:10
So currently the bug is ERR_HTTP2_PROTOCOL_ERROR which caused the failed requests? I saw 88.png is partial, does the 'half' image issue persist?

**Comment by skinkie** [comment] 2020-04-24 00:17
@jiangwenyuan I think you have consistently resolved the disk cache issue. Because it seems that I can always query the complete file by open in a new tab and hit F5, even if it initial download would give me a partial download. So that still brings us to the ERR_HTTP2_PROTOCOL_ERROR problem.

**Comment by jiangwenyuan** [comment] 2020-04-24 08:35
You're right, it's very difficult to reproduce, the ERR_HTTP2_PROTOCOL_ERROR never occurs here.

When ERR_HTTP2_PROTOCOL_ERROR happens, can you try follows?

```
 curl -v --http2 {The failed request url}
 curl -v --http1.1 {The failed request url}
```

**Comment by jiangwenyuan** [comment] 2020-05-01 01:34
I'm closing this issue since the partial cache issue has been fixed.

Feel free to create a new issue if the ERR_HTTP2_PROTOCOL_ERROR occurs again.

**Closed by jiangwenyuan** 2020-05-01 01:34 UTC
Labels: bug, investigation
