### ISSUE TITLE
Suspicious cpu activity

### ISSUE THREAD

**Issue by aleksystasiak** [jiangwenyuan/nuster#97] opened 2020-09-02 07:06 UTC
Hello
I'm using nuster version 5.2.2.22
While everything is working as expected I noticed that on every machine where nuster runs 1 cpu core has always 100% use.
It does not matter if nuster is doing any work, it's just always on 100% and it's always one core.
Is that expected behaviour ? 

I'm running nuster as systemd service in master-worker mode with nbthread enabled.

```
haproxy -vv
nuster version 5.2.2.22
Copyright (C) 2017-present, Jiang Wenyuan, <koubunen AT gmail DOT com >

HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PTHREAD_PSHARED=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by jiangwenyuan** [comment] 2020-09-02 10:17
@aleksystasiak Thanks, can you share the config file(remove sensitive data if any)?

**Comment by aleksystasiak** [comment] 2020-09-02 12:04
```
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        master-worker
        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private
        nuster cache on data-size 9000m dict-size 1648576
        nuster manager on uri /_nuster purge-method PURGEX
        tune.maxrewrite 32768
        tune.bufsize 65536
        nbthread 4
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend render
bind 172.16.34.38:8099
mode http
default_backend docker

frontend imgproxy
bind 172.16.34.38:80
#http-request replace-uri \/i\/(\d+)x(\d+)\/(.*) \/resize:fit:\1:\2:0\/plain\/\3
#http-request    set-var(txn.host)   req.hdr(host),lower,field(1,:)
#http-request set-var(txn.path) path
#http-request    track-sc0    var(txn.path)  table BK_ALL
#use_backend imgproxy if { sc0_http_req_cnt gt 5 }
default_backend imgproxy-wc

frontend nginx
bind 172.16.34.38:2080
#http-request replace-uri \/i\/(\d+)x(\d+)\/(.*) \/resize:fill:\1:\2:0\/plain\/\3
default_backend nginx


backend docker
mode http
stats enable
stats uri /nstats

server render-1 127.0.0.1:8099

backend imgproxy
mode http
nuster cache on
nuster rule all ttl 1d
http-response set-header x-cache-nuster hit if { nuster.cache.hit }

#http-request set-path /resize:fill:300:400:0/plain%[path]
server proxy-1 172.16.34.38:8080

backend imgproxy-wc
mode http


#http-request set-path /resize:fill:300:400:0/plain%[path]
server proxy-1 172.16.34.38:8080


backend nginx
mode http
#http-request set-path /resize:fill:300:400:0/plain%[path]

server proxy-1 172.16.34.38:1080
```

**Comment by aleksystasiak** [comment] 2020-09-02 12:10
Kinda off topic but look at tracking requests by path in commented section of imgproxy frontend and commented table in BK_ALL, something like this could be internal nuster function (cache only if url hits > n)

**Comment by jiangwenyuan** [comment] 2020-09-02 12:29
@aleksystasiak Thanks, how to trigger this bug? I started with this config, but failed reproducing.

Does it happen as soon as you start the program? Does it happen if you start it directly instead of systemd(./haproxy -f conf)? Is the master process or worker process using 100% CPU?

**Comment by aleksystasiak** [comment] 2020-09-02 12:40
Yes, as soon I start nuster one core is at 100% used. I'm starting using systemd and standard haproxy systemd service.
Just now, I changed config and service file to disable master-worker mode - still same result from service.
Running manually (with nohup)  both in master-worker mode and without yields same result as from service.

**Comment by aleksystasiak** [comment] 2020-09-02 12:41
![Zrzut ekranu z 2020-09-02 14-40-51](https://user-images.githubusercontent.com/23705608/91982372-71178e80-ed2a-11ea-869f-c7b338471fb9.png)

**Comment by jiangwenyuan** [comment] 2020-09-02 13:02
@aleksystasiak Seems it's a haproxy bug, can you remove `-s` and see what happens?

**Comment by aleksystasiak** [comment] 2020-09-02 13:11
I may be wrong but it seems debian buster is only os on which I see problem, just compiled same version under ubuntu 20.04 and it seems to work fine.

**Comment by jiangwenyuan** [comment] 2020-09-02 13:13
Can you check the haproxy parameters by `ps` to see if there's `-s`? I can reproduce using haproxy v2.3 master  by `haproxy -f -c config`

**Comment by aleksystasiak** [comment] 2020-09-02 13:19
After introducing config attached here, I see 100% cpu on ubuntu.
As for starting parameters, haproxy refuses to start if I try to run it manually without any parameters besides config file (with master-worker commented out)
Running with -s seems to start haproxy but it does not work.
Running with -W or -Ws (or master-worker in config) causes cpu problem.

**Comment by jiangwenyuan** [comment] 2020-09-02 13:29
`master-worker` or `-W` is needed by nuster. just remove `-s` and see if it still happens.

**Comment by aleksystasiak** [comment] 2020-09-02 13:31
![Zrzut ekranu z 2020-09-02 15-31-12](https://user-images.githubusercontent.com/23705608/91989904-5b599780-ed31-11ea-9b63-c5922746861f.png)

**Comment by jiangwenyuan** [comment] 2020-09-02 13:44
Weird. I cannot reproduce using above config file. Exactly same config file?
Can you gdb the process?

BTW, I've raised the `-s` bug: https://github.com/haproxy/haproxy/issues/837

**Comment by aleksystasiak** [comment] 2020-09-02 13:58
I don't know how to use gdb, it complains about missing sources when I try to attach it to process.
Strace produces:
```
root@aleksys-dell:/home/aleksys# strace -p 18328 -s 4096 -f
strace: Process 18328 attached with 2 threads
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69194864}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69242652}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69284010}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69322334}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69415049}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69508842}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69579773}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69619980}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69694985}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69735159}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69812469}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69850767}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69920142}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=69961103}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70025276}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70087633}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70178112}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70216279}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70286172}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70351611}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70413081}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70451401}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70526604}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70567310}) = 0
[pid 18328] epoll_wait(4, [], 200, 1000) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70627308}) = 0
[pid 18328] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=70664307}) = 0
[pid 18328] epoll_wait(4, ^Cstrace: Process 18328 detached
 <detached ...>
strace: Process 18329 detached
```

**Comment by aleksystasiak** [comment] 2020-09-02 14:00
Config file is identical, only frontends bind addr are different.
The same sections are commented out.

**Comment by aleksystasiak** [comment] 2020-09-02 14:12
Also a sidenote, removing s from -Ws causes issues when using systemd service. (Probablu because it enables notifications for systemd)

**Comment by jiangwenyuan** [comment] 2020-09-02 23:57
@aleksystasiak Unable to reproduce and seems nothing suspicious. Can you git clone the repo and check again?

```
git clone https://github.com/jiangwenyuan/nuster.git
cd nuster
git checkout 5.2
make -j $(nproc) TARGET=linux-glibc  USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 V=1 -f Makefile
./haproxy -W -f /etc/haproxy/haproxy.cfg # this should be OK
./haproxy -s -W -f /etc/haproxy/haproxy.cfg # this should cause 100% CPU
```

And the `-s` bug has been fixed in haproxy and I have patched in https://github.com/jiangwenyuan/nuster/tree/issue97
Can you also verify with this branch?

**Comment by aleksystasiak** [comment] 2020-09-03 07:59
Cloned and compiled according to instructions:
```
aleksys    16320  0.0  0.0  13400  4968 pts/0    Ss   09:38   0:00      \_ bash
root       16326  0.0  0.0  14864  4904 pts/0    S    09:38   0:00      |   \_ sudo su
root       16328  0.0  0.0  13552  4296 pts/0    S    09:38   0:00      |       \_ su
root       16329  0.0  0.0  12544  4248 pts/0    S    09:38   0:00      |           \_ bash
root       16991 98.8  0.4 9343340 80068 pts/0   Sl+  09:42   0:57      |               \_ ./haproxy -W -f /etc/haproxy/haproxy.cfg
haproxy    16993  0.0  0.4 9568640 68320 pts/0   Sl+  09:42   0:00      |                   \_ ./haproxy -W -f /etc/haproxy/haproxy.cfg

```

```
root@aleksys-dell:/opt/nuster/nuster# gdb -p 16991
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 16991
[New LWP 16992]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f7548bf143e in epoll_wait (epfd=4, events=0x55ee88060620, maxevents=200, timeout=timeout@entry=1000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Nie ma takiego pliku ani katalogu. #  <- It's No such file or directory
(gdb) 

```

**Comment by aleksystasiak** [comment] 2020-09-03 11:53
I managed to start nuster through dbg, what to do next ?

**Comment by jiangwenyuan** [comment] 2020-09-03 13:21
type `n` and multiple `enter`

**Comment by aleksystasiak** [comment] 2020-09-03 13:28
```
(gdb) n
_do_poll (p=<optimized out>, exp=0, wake=0) at src/ev_epoll.c:196
196                     tv_update_date(timeout, status);
(gdb)
198                     if (status) {
(gdb)
199                             activity[tid].poll_io++;
(gdb)
200                             break;
(gdb)
210             tv_leaving_poll(wait_time, status);
(gdb)
212             thread_harmless_end();
(gdb)
213             if (sleeping_thread_mask & tid_bit)
(gdb)
214                     _HA_ATOMIC_AND(&sleeping_thread_mask, ~tid_bit);
(gdb)
run_poll_loop () at src/haproxy.c:3002
3002                    nuster_housekeeping();
(gdb)
3004                    activity[tid].loops++;
(gdb)
2943                    wake_expired_tasks();
(gdb)
2947                    if (signal_queue_len && tid == 0) {
(gdb)
2948                            activity[tid].wake_signal++;
(gdb)
2949                            signal_process_queue();
(gdb)
[NOTICE] 246/152758 (13986) : haproxy version is 2.2.2
[NOTICE] 246/152758 (13986) : path to executable is /usr/sbin/haproxy
[ALERT] 246/152758 (13986) : Current worker #1 (13988) exited with code 130 (Interrupt)
[WARNING] 246/152758 (13986) : All workers exited. Exiting... (130)
[Thread 0x7ffdbe94c700 (LWP 13987) exited]
[Inferior 1 (process 13986) exited with code 0202]

```

**Comment by jiangwenyuan** [comment] 2020-09-03 13:34
@aleksystasiak  16991 seems normal. Can you type more enter until `cur_poller.poll(&cur_poller, next, wake);`, should hang there for 1 second.

Both 16991 and 16993 use 100% CPU? and can you try 16993 also?

**Comment by aleksystasiak** [comment] 2020-09-03 13:43
This time its 14018 and 14020
14018:
```
3002                    nuster_housekeeping();
(gdb)
3004                    activity[tid].loops++;
(gdb)
2943                    wake_expired_tasks();
(gdb)
2947                    if (signal_queue_len && tid == 0) {
(gdb)
2953                    process_runnable_tasks();
(gdb)
2956                    if (killed > 1)
(gdb)
2961                    if (thread_has_tasks())
(gdb)
2964                            _HA_ATOMIC_OR(&sleeping_thread_mask, tid_bit);
(gdb)
2966                            if (thread_has_tasks()) {
(gdb)
2976                            if (stopping) {
(gdb)
2986                            if ((jobs - unstoppable_jobs) == 0 &&
(gdb)
3000                    cur_poller.poll(&cur_poller, next, wake);
(gdb)
3002                    nuster_housekeeping();

```
14020:
```
3002                    nuster_housekeeping();
(gdb)
3004                    activity[tid].loops++;
(gdb)
2943                    wake_expired_tasks();
(gdb)
2947                    if (signal_queue_len && tid == 0) {
(gdb)
2953                    process_runnable_tasks();
(gdb)
2956                    if (killed > 1)
(gdb)
2961                    if (thread_has_tasks())
(gdb)
2964                            _HA_ATOMIC_OR(&sleeping_thread_mask, tid_bit);
(gdb)
2966                            if (thread_has_tasks()) {
(gdb)
2976                            if (stopping) {
(gdb)
2986                            if ((jobs - unstoppable_jobs) == 0 &&
(gdb)
3000                    cur_poller.poll(&cur_poller, next, wake);
(gdb)


3002                    nuster_housekeeping();
```
14018 takes 100% of one core as usual (actually about 80% this time - don't know why) and burns cpu time
14020 does not use cpu at all (because there is no traffic i presume)

**Comment by jiangwenyuan** [comment] 2020-09-03 13:45
Thanks, can you do more enter  in 14018 gdb and check if `3000                    cur_poller.poll(&cur_poller, next, wake);` hangs for 1 second?

**Comment by aleksystasiak** [comment] 2020-09-03 13:46
Yes it does hang a little while in comparison to other steps

**Comment by aleksystasiak** [comment] 2020-09-03 13:48
![Zrzut ekranu z 2020-09-03 15-48-00](https://user-images.githubusercontent.com/23705608/92123388-df2c8600-edfc-11ea-8474-23f059500bfb.png)

**Comment by jiangwenyuan** [comment] 2020-09-03 13:53
Hmm...then how come the master uses ~100% CPU usage...

**Comment by jiangwenyuan** [comment] 2020-09-03 13:55
Do you mind send me the exact config file(/etc/haproxy/haproxy.cfg) without any redaction to my email?

**Comment by aleksystasiak** [comment] 2020-09-03 14:05
Did you get it ?

**Comment by jiangwenyuan** [comment] 2020-09-03 14:16
Yes, thanks a lot. and confirm 100% usage!

**Comment by jiangwenyuan** [comment] 2020-09-03 14:44
@aleksystasiak As a temporary workaround, append `dir /any/path` to `        nuster cache on data-size 9000m dict-size 1648576
`

**Comment by aleksystasiak** [comment] 2020-09-03 15:38
Workaround does the trick.
Thank you

**Comment by jiangwenyuan** [comment] 2020-09-04 09:25
@aleksystasiak Thank you so much for the help, I've fixed and pushed to 5.2 branch.

**Comment by jiangwenyuan** [comment] 2020-09-06 03:10
Feel free to reopen if the bug still persists.

**Closed by jiangwenyuan** 2020-09-06 03:10 UTC
Labels: bug

**Comment by dario30186** [comment] 2020-09-27 16:39
hello @jiangwenyuan ,
could you build docker image with the fix and push it in https://hub.docker.com/r/nuster/nuster pls ?

**Comment by jiangwenyuan** [comment] 2020-09-28 06:28
@dario30186 Yes, I will release a new version today.
