### ISSUE TITLE
Too many cache misses

### ISSUE THREAD

**Issue by igorescobar** [jiangwenyuan/nuster#82] opened 2020-05-21 17:23 UTC
Hi,

Sorry to bother you guys again. But I'm having way too many cache misses on our setup. 

On this issue (#76), you gave a pretty detailed explanation on how the cache lookup works and after setting up I wasn't expecting to see too many cache misses. So this is my current setup:

```
global
  maxconn 100000
  nuster cache on data-size 500m dict-size 500m dir /nuster/cache disk-loader 500000 disk-saver 50000
  log stdout local0 info
  master-worker

defaults
  log global
  mode http
  log-format '{"time":{"tr":%Tr,"tq":%Tq,"tw":%Tw,"tc":%Tc,"tt":%Tt},"haproxy":{"retries":%rc,"request":{"method":"%HM","uri":"%[capture.req.uri]","protocol":"%HV","header":{"host":"%[capture.req.hdr(0),json(utf8s)]","xforwardfor":"%[capture.req.hdr(1),json(utf8s)]","referer":"%[capture.req.hdr(2),json(utf8s)]"}},"name":{"server":"%s"},"response":{"status_code":%ST,"header":{"xrequestid":"%[capture.res.hdr(0),json(utf8s)]"}},"bytes":{"uploaded":%U,"read":%B}}}'
  option http-keep-alive

  retries 1
  option redispatch
  timeout http-keep-alive  72s
  timeout client           72s
  timeout connect          72s
  timeout server           72s
frontend fe
  bind *:3001
  default_backend be
backend be
  nuster cache on
  nuster rule r0 memory off disk on use-stale on wait on key method.scheme.host.path ttl 12d if { res.hdr(Content-Type) -m beg image/ }
  http-response set-header x-cache HIT if { nuster.cache.hit }
  server s1 localhost:3000
```

And this is pretty much how it looks like after a container restart:
```
**NUSTER**
nuster.cache:                   on
nuster.nosql:                   off
nuster.manager:                 on

**DICT**
dict.cache.size:                524288000
dict.cache.length:              65536000
dict.cache.used:                6481
dict.cache.cleanup_idx:         570282
dict.cache.sync_idx:            0

**STORE MEMORY**
store.memory.cache.size:        1048576000
store.memory.cache.used:        530215168
store.memory.cache.count:       0

**STORE DISK**
store.disk.cache.dir:           /nuster/cache
store.disk.cache.loaded:        no

**STATS**
stats.cache.total:              5800
stats.cache.hit:                156
stats.cache.fetch:              5435
stats.cache.abort:              0
stats.cache.bytes:              3435804

**PROXY cache be**
be.rule.r0:                     state=on  memory=off disk=on   ttl=1036800
```

And this is the output when the server starts:
```
2020-05-21T17:15:04.003Z
[NOTICE] 141/171503 (1) : [nuster][cache] on, dict_size=524288000, data_size=524288000
2020-05-21T17:15:04.003Z
<133>May 21 17:15:03 nuster[1]: Proxy fe started.
2020-05-21T17:15:04.003Z
<133>May 21 17:15:03 nuster[1]: Proxy be started.
```

Have in mind that we have auto-scaling and the container where `Nuster` is available it restarts a lot, a few times per hour. Worth mentioning that at this moment, the cache folder is around 16.0 GiB.

I was expecting that... once the file is saved... it would never happen a cache miss again regardless if the container just started or not but it seems that this is not the case.

I can see files with cache miss 6 times on the last hour that was already persisted on the cache folder.

Thoughts?

**Comment by jiangwenyuan** [comment] 2020-05-22 00:51
@igorescobar 

> we have auto-scaling 

How many containers may you have at the same time? >= 1? Because you mentioned in the EFS issue, I think there would be no problem in case of multiple containers but have not done any test. I'm going to have multiple docker containers running in local mounting same volume, let's see what happens.

Meanwhile,  could you help test with `wait on` and/or `use-stale on` deleted. And when `wait on` deleted, can you also enable `debug` and send the log to me(use email if that's private).

**Comment by igorescobar** [comment] 2020-05-22 08:41
Yes, it's more then one. Another super weird thing that it is happening:
<img width="1605" alt="Screenshot 2020-05-22 at 09 30 05" src="https://user-images.githubusercontent.com/24032/82648828-37ee5f00-9c10-11ea-8e54-1a5598a999f2.png">

During the day it happens that Nuster completely ignores the disk and only after restarting the containers it starts using the disks again. Notice the interruptions on the graph above.

**Comment by igorescobar** [comment] 2020-05-22 09:01
Also, I managed to do some tests yesterday and if I target a file right after a new container becomes available I got several consecutive misses on a file that was already cached.

For me, it seems that, while Nuster is loading the cache into memory it can only deliver things that are on that index that Nuster is building everything outside of that Nuster isn't looking for the disk files.

**Comment by jiangwenyuan** [comment] 2020-05-22 09:09
Hmm, there cannot be several consecutive misses. Even if nuster failed to sever the cache which does not be loaded, there should be only one miss.

I don't know, maybe it's something with ECS/EFS.

**Comment by igorescobar** [comment] 2020-05-22 09:59
@jiangwenyuan can I configure the frequency of each interaction with the disk?

```
**NUSTER**
nuster.cache:                   on
nuster.nosql:                   off
nuster.manager:                 on

**MANAGER**
manager.uri:                    /internal/nuster
manager.purge_method:           PURGE

**DICT**
dict.cache.size:                524288000
dict.cache.length:              65536000
dict.cache.used:                8358
dict.cache.cleanup_idx:         653925
dict.cache.sync_idx:            0

**STORE MEMORY**
store.memory.cache.size:        1048576000
store.memory.cache.used:        531616384
store.memory.cache.count:       0

**STORE DISK**
store.disk.cache.dir:           /nuster/cache
store.disk.cache.loaded:        no

**STATS**
stats.cache.total:              8331
stats.cache.hit:                997
stats.cache.fetch:              7145
stats.cache.abort:              0
stats.cache.bytes:              12378125

**PROXY cache be**
be.rule.r0:                     state=on  memory=off disk=on   ttl=1036800
```

It seems that nuster is taking quite some time to load all the files into memory. The disk has ~30GiB and we are already a few minutes in and it seems like we only have only 8k files into the hash table?

**Comment by igorescobar** [comment] 2020-05-22 10:27
Is it 10ms?
https://github.com/jiangwenyuan/nuster/blob/ef63e5e0b0cf862e66fcba46e58a029a96954389/src/nuster/cache/engine.c#L349

If it's that's definitely too low for my use case. Nginx allows you to do something like this:
```
proxy_cache_path /nginx/cache levels=1:2 keys_zone=ib_cache:1024m max_size=500g inactive=7d loader_files=300000 loader_threshold=10000 use_temp_path=off;
```

So `loader_files=300000 loader_threshold=10000` it means I want to load up to 300000 into memory until it hits the `loader_threshold` time.

**Comment by igorescobar** [comment] 2020-05-22 11:23
I tried to point to the `stable` docker version, a few minutes in and this happened:

------------------------------------------------------------------------------------------
|                                        @message                                        |
|----------------------------------------------------------------------------------------|
| Thread 3 is about to kill the process.                                                 |
|  >Thread 1 : act=0 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0                                 |
|              stuck=1 prof=1 harmless=0 wantrdv=0                                       |
|              cpu_ns: poll=7006060275 now=8324889374 diff=1318829099                    |
|              curr_task=0x7ffa9811b480 (task) calls=2 last=3146492896 ns ago            |
|                fct=0x562e9aad09c0=main+316784 (process_stream) ctx=0x562e9bb9bf30      |
|              strm=0x562e9bb9bf30 src=172.31.89.33 fe=fe be=be dst=unknown              |
|              rqf=64808002 rqa=4c000 rpf=80000000 rpa=0 sif=EST,200028 sib=INI,30       |
|              af=(nil),0 csf=0x7ffa940fb870,10c000                                      |
|              ab=(nil),0 csb=(nil),0                                                    |
|              cof=0x7ffa98047770,80201300:H1(0x7ffa940738e0)/RAW((nil))/tcpv4(19096)    |
|              cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0)                               |
|   Thread 2 : act=0 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0                                 |
|              stuck=0 prof=1 harmless=0 wantrdv=0                                       |
|              cpu_ns: poll=6079418711 now=7557662268 diff=1478243557                    |
|              curr_task=0x562e9bb9cc20 (task) calls=1 last=2994836643 ns ago            |
|                fct=0x562e9aad09c0=main+316784 (process_stream) ctx=0x7ffa94050130      |
|              strm=0x7ffa94050130 src=172.31.15.0 fe=fe be=be dst=unknown               |
|              rqf=64d08002 rqa=4c000 rpf=80000000 rpa=0 sif=EST,10020 sib=INI,30        |
|              af=(nil),0 csf=0x7ffa90101a40,c000                                        |
|              ab=(nil),0 csb=(nil),0                                                    |
|              cof=0x7ffa98048330,80201300:H1(0x7ffa900413a0)/RAW((nil))/tcpv4(22742)    |
|              cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0)                               |
| *>Thread 3 : act=0 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0                                 |
|              stuck=1 prof=1 harmless=0 wantrdv=0                                       |
|              cpu_ns: poll=6903328489 now=9034020433 diff=2130691944                    |
|              curr_task=0x562e9bb2fcc0 (task) calls=2 last=3855947148 ns ago            |
|                fct=0x562e9aad09c0=main+316784 (process_stream) ctx=0x562e9bb2eb70      |
|              strm=0x562e9bb2eb70 src=172.31.79.120 fe=fe be=be dst=unknown             |
|              rqf=64808002 rqa=4c000 rpf=80000000 rpa=0 sif=EST,200028 sib=INI,30       |
|              af=(nil),0 csf=0x7ffa90046340,10c000                                      |
|              ab=(nil),0 csb=(nil),0                                                    |
|              cof=0x7ffa9806bd00,80201300:H1(0x7ffa980bf770)/RAW((nil))/tcpv4(19329)    |
|              cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0)                               |
|  >Thread 4 : act=0 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0                                 |
|              stuck=1 prof=1 harmless=0 wantrdv=0                                       |
|              cpu_ns: poll=10823702237 now=12980802608 diff=2157100371                  |
|              curr_task=0x7ffa940ebca0 (task) calls=2 last=3878205367 ns ago            |
|                fct=0x562e9aad09c0=main+316784 (process_stream) ctx=0x7ffa940e6c70      |
|              strm=0x7ffa940e6c70 src=172.31.63.240 fe=fe be=be dst=unknown             |
|              rqf=64808002 rqa=4c000 rpf=80000000 rpa=0 sif=EST,200028 sib=INI,30       |
|              af=(nil),0 csf=0x7ffa980d46c0,10c000                                      |
|              ab=(nil),0 csb=(nil),0                                                    |
|              cof=0x7ffa94053e00,80201300:H1(0x7ffa90047b00)/RAW((nil))/tcpv4(16253)    |
|              cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0)                               |
| <133>May 22 11:00:10 nuster[1]: Proxy fe started.                                      |
| <133>May 22 11:00:10 nuster[1]: Proxy be started.                                      |
| [NOTICE] 142/110010 (1) : New worker #1 (9) forked                                     |
| [NOTICE] 142/110010 (1) : [nuster][cache] on, dict_size=524288000, data_size=524288000 |
| [WARNING] 142/102050 (1) : Exiting Master process...                                   |
------------------------------------------------------------------------------------------

This basically made everything crash.

**Comment by jiangwenyuan** [comment] 2020-05-22 11:32
Yes, it's max 10ms. Probably I should add some option to control this time.

**Comment by igorescobar** [comment] 2020-05-22 13:01
@jiangwenyuan FYI, after removing the flags `use-stale on wait on` disk consumption seems to be steady not more cut-offs and cache performance seems to be getting better.

Just so you know how those `10ms` affects the load of the disk... 1+ hours later and I still don't have all files on the hash table:
```
**NUSTER**
nuster.cache:                   on
nuster.nosql:                   off
nuster.manager:                 on

**MANAGER**
manager.uri:                    /internal/nuster
manager.purge_method:           PURGE

**DICT**
dict.cache.size:                524288000
dict.cache.length:              65536000
dict.cache.used:                60925
dict.cache.cleanup_idx:         5009708
dict.cache.sync_idx:            0

**STORE MEMORY**
store.memory.cache.size:        1048576000
store.memory.cache.used:        578806016
store.memory.cache.count:       0

**STORE DISK**
store.disk.cache.dir:           /nuster/cache
store.disk.cache.loaded:        no

**STATS**
stats.cache.total:              78031
stats.cache.hit:                25328
stats.cache.fetch:              51204
stats.cache.abort:              0
stats.cache.bytes:              145270527

**PROXY cache be**
be.rule.r0:                     state=on  memory=off disk=on   ttl=1036800
```

Can you double-check if `Nuster` really checks the disk while `store.disk.cache.loaded` is false? I'm asking because if this "fallback" is really working as expected cache misses should never happen once the file was saved.

**Comment by igorescobar** [comment] 2020-05-22 13:04
Ops... it stopped reading the disk again for no clear reason:
![Screenshot 2020-05-22 at 14 04 01](https://user-images.githubusercontent.com/24032/82670505-2bc8c880-9c35-11ea-84fe-27ca44248483.png)

**Comment by jiangwenyuan** [comment] 2020-05-22 13:27
@igorescobar Thanks a lot for the testing.

> Can you double-check if Nuster really checks the disk while store.disk.cache.loaded is false?

Yes, if you can build from source and test in local, you can put `return;` here:
https://github.com/jiangwenyuan/nuster/blob/master/src/nuster/store/disk.c#L403
so the disk will not be loaded to memory.

And you can enable `debug` to do some test.

**Comment by igorescobar** [comment] 2020-05-22 13:41
@jiangwenyuan It could be 500k, it millions :)

**Comment by igorescobar** [comment] 2020-05-22 13:46
What about the disk_cleanup?

https://github.com/jiangwenyuan/nuster/blob/master/src/nuster/store/disk.c#L602

I noticed that it only starts after the disk is loaded too. Do you think that this might be the reason why the read/write gets cutoff after a few hours?

**Comment by jiangwenyuan** [comment] 2020-05-22 13:52
> It could be 500k or millions :)

I see. and how about the file size? So I could do the test with similar env.

> I noticed that it only starts after the disk is loaded too. Do you think that this might be the reason why the read/write gets cutoff after a few hours?

disk_cleanup checks the disk cache file's validity and remove that if invalid.

**Comment by igorescobar** [comment] 2020-05-22 13:54
> I see. and how about the file size? So I could do the test with similar env.

They are all images so it could be a few kb to a few mbs.

>  disk_cleanup checks the disk cache file's validity and remove that if invalid.

Worth mentioning that immediately after Nuster stops using the disk for read/write all requests starts to be a CACHE MISS.

**Comment by igorescobar** [comment] 2020-05-22 14:37
And again... It seems that it always happens around the same time...

![Screenshot 2020-05-22 at 15 35 14](https://user-images.githubusercontent.com/24032/82678698-f2e32080-9c41-11ea-95c0-772afb26474d.png)

**Comment by igorescobar** [comment] 2020-05-22 14:39
I'm starting to think that it might be related to that FD leak you mentioned.

**Comment by jiangwenyuan** [comment] 2020-05-22 15:15
~12:50: container restart time?

**Comment by igorescobar** [comment] 2020-05-22 15:26
The container restarted 2 minutes before you start seeing disk activity on the graph

**Comment by igorescobar** [comment] 2020-05-22 15:29
I didn't noticed before because I was running 2+ containers with one core and then a changed to 1+ containers with two cores instead to reduce the auto scaling triggers (just to test if this would impact the cache miss).

But now that I'm running with 2+ containers it could happen that I have one container working and another one that doesn't. That explain the high level of cache misses.

**Comment by jiangwenyuan** [comment] 2020-05-23 03:09
@igorescobar I just found out that the docker image nuster/nuster:v5.0.9.21 build failed. So you are probably using nuster/nuster:v5.0.8.21 which deletes disk cache file when `use-stale on` is set on load

**Comment by jiangwenyuan** [comment] 2020-05-23 04:43
Tested in local with 2 containers mounting same directory and works fine. I'm going to generate more data. No fd leaks found yet.

**Comment by igorescobar** [comment] 2020-05-23 08:56
The problem also happens with only one container btw. That's why I found
that issue that it wasn't using the disk anymore.

**Comment by igorescobar** [comment] 2020-05-23 08:57
Worth mentioning that I wasn't using the use stale flag anymore since your
recommendation.

**Comment by igorescobar** [comment] 2020-05-23 13:27
Test in progress.

**Comment by igorescobar** [comment] 2020-05-24 08:54
So, yeah, the issue was definitely the one spotted on #80. Now that the application is using the disk correctly

![Screenshot 2020-05-24 at 09 45 45](https://user-images.githubusercontent.com/24032/82749914-6735d500-9da4-11ea-94a5-35399834058d.png)

Nuster is now working as described. 🎉

**Comment by igorescobar** [comment] 2020-05-24 08:55
Thanks @jiangwenyuan ! Well done!

**Comment by jiangwenyuan** [comment] 2020-05-24 10:13
Thanks a lot for testing:)

**Comment by jiangwenyuan** [comment] 2020-05-25 12:23
Released v5.0.10.21. Closing now, feel free to reopen if the issue persists

**Closed by jiangwenyuan** 2020-05-25 12:23 UTC
Labels: bug, investigation

**Comment by igorescobar** [comment] 2020-05-28 08:27
Well, not sure why but I started to see those drops again on disk usage:
<img width="1591" alt="Screenshot 2020-05-28 at 09 25 53" src="https://user-images.githubusercontent.com/24032/83117661-497aaf80-a0c5-11ea-8490-ba47a7289a72.png">

I removed the flag "wait on" because it was something I added later... just to see if it gets better but I believe there is something removing stuff from disk again and causing cache MISS.

**Comment by jiangwenyuan** [comment] 2020-05-28 08:31
Which part?

**Comment by igorescobar** [comment] 2020-05-28 08:36
The parts where the writes west to almost zero and the read dropped A LOT.

**Comment by jiangwenyuan** [comment] 2020-05-28 08:47
Is there any other suspicious logs/behavious? Is that overall read/write of all containers? Any traffics changes between that time slot?

**Comment by igorescobar** [comment] 2020-05-28 09:13
Yes, it's the overall for all containers. Traffic is the same. I think it just didn't go to 0 because one of the containers was still fine and the other don't.

**Comment by jiangwenyuan** [comment] 2020-05-28 09:48
Are you mean before 12:00, there were 2 containers and between 12:00~13:00 there were only 1 container and increased to 2 after 13:00?

**Comment by igorescobar** [comment] 2020-05-28 09:51
Not really. During the entire time on this graph, two containers were delivering requests. But the "bug" could only happen in only one of them and that's why on the graph you don't see a drop to 0 but just a BIG drop.

**Comment by igorescobar** [comment] 2020-05-28 09:54
Worth mentioning that once this started to happen again the cache size was always around 30GiB and when it wasn't happening the cache easily hit 50GiB. I removed the "wait on" flag and so far it's working. I will wait a few more hours and share the results.

**Comment by jiangwenyuan** [comment] 2020-05-28 09:57
~12:00: cache directory size was 50G
12 ~ 13: cache directory size drops to 30G
13:00~: cache directory size grows back to 50G?

**Comment by igorescobar** [comment] 2020-05-28 10:07
Let me explain a bit better.
Before using those flags, the cache was around 50GiB. Since everything was going fine I decided to start fine tune the configs. and then I decided to add the `wait on`, `clean-temp on`, and deactivate the logs because of the other bug. 

Then you mentioned that the `clean-temp on` wasn't going to work well for my case since we have more than one container using the same cache dir and I mentioned that before activating these the cached dir dropped from 50 to 25-30 very fast and I started to have more cache miss.

I removed the clear-temp and the logs later because of that but the cache never went back to normal (to the 50+ range). 

After that... I started to see these drops on the disk usage again and this is the current situation.

~3 hours ago I removed the `wait on` flag to see if I got better results. So far, the read/write is steady and the cache dir increasing. I'm going to wait a few more to see if it stays like this.

**Comment by igorescobar** [comment] 2020-05-28 10:09
> And sicne the ttl is 12day, some unexpected deletions happened?

I'm not using `Nuster` for 12 days. No deletions should happen.

**Comment by igorescobar** [comment] 2020-05-29 09:44
Here it is what happened:

Removing the `wait on` didn't do anything. I also tried to use the latest docker image on DockerHub and the problem are still happening. It might be happening with less frequency but still happening. 

The disk stop to be used until the auto-scaling kicks in and replace the container.

**Comment by jiangwenyuan** [comment] 2020-05-29 10:45
What exactly does `The disk stop to be used` mean? So between 12~13 we observed read drop and no write. Does the container still response? You mentioned cache miss increasing, if that's true, which means the container is alive and cannot find cache in disk hence fetch from origin and save to disk, in this case, there must be some write happen.

Are you able to do some testing against containers during the `read drop`? like test the cache creation, etc?

**Comment by igorescobar** [comment] 2020-05-29 11:42
It happens the same thing as before when we were discussing FD leak issue. For some reason, `Nuster` stops using the disk for reads and writes and all requests starts to be a CACHE MISS.

**Comment by igorescobar** [comment] 2020-05-29 11:43
It just seems to be happening with a bigger time interval.

**Comment by jiangwenyuan** [comment] 2020-05-29 12:52
Hmm, how do you generate the traffic? unable to reproduce In my test env( using wrk lua script)

**Comment by igorescobar** [comment] 2020-05-29 13:00
Unfortunately, it's a % of my production traffic. 😅

**Comment by jiangwenyuan** [comment] 2020-05-31 23:59
Stress tested for 2 days, both CPU and disk IO were pretty steady.

**Comment by igorescobar** [comment] 2020-06-01 08:14
I appreciate the effort @jiangwenyuan. Unfortunately, there isn't much else I can add to this. I will give Nuster a try again in a few months and let's see what happens.

**Comment by jiangwenyuan** [comment] 2020-06-01 08:19
@igorescobar Thank you so much for the testing:)
